### PR TITLE
Updated to 1.20.1

### PR DESCRIPTION
**Pull request by feandrad**

### CODE REVIEW

**Comment by leclerc-leo** [comment]
Hello, 

Thanks for the commit and pull request.
I will look it up tonight when I'm home

Léo

**Comment by leclerc-leo** [comment]
From what i read through and testing it worked perfectly.

Thanks a lot.

**Comment by feandrad** [comment]
Awesome! I am using this mod in my personal server. Is really cool, had some issues with the sync function and some mods though. Is there  a server config option to disable that command for no op users? If not that could be an enchancement I would appreciate!

Keep up the good work!

**Comment by leclerc-leo** [comment]
I will probably begin working again on it since I don't have much to do rn. 

Next would be a log to debug when users have some problem, but I never really thought of configs which could be pretty easy to implement. I'll see what I can do.

**Comment by leclerc-leo** [comment]
The new version with a basic config file is at https://legacy.curseforge.com/minecraft/mc-mods/building-dimension/files/4740566

I'll work on the debug file next, If you have any issues you can send it to me in discord at l.dev or create an issue on github

**Pull request merged**
